const finalizedOffers = [
  [
    {
      id: 1,
      title: 'T-shirt Nike Pietro',
      subtitle: 'Pietro de Alchimist',
      date: Date.now(),
      image: 'https://picsum.photos/500',
      price: 2000,
    },
    {
      id: 2,
      title: 'Polo',
      subtitle: 'Pietro de Alchimist',
      date: Date.now(),
      image: 'https://picsum.photos/500',
      price: 2000,
    },
  ],
  [
    {
      id: 3,
      title: 'Pantalon',
      subtitle: 'Pietro de Alchimist',
      date: Date.now() - 200000000,
      image: 'https://picsum.photos/500',
      price: 2000,
    },
    {
      id: 4,
      title: 'Slip',
      subtitle: 'Pietro de Alchimist',
      date: Date.now() - 200000000,
      image: 'https://picsum.photos/500',
      price: 2000,
    },
    {
      id: 5,
      title: 'Raquette de tennis',
      subtitle: 'Pietro de Alchimist',
      date: Date.now() - 200000000,
      image: 'https://picsum.photos/500',
      price: 2000,
    },
  ],
  [
    {
      id: 6,
      title: 'Chaussettes',
      subtitle: 'Pietro de Alchimist',
      date: Date.now() - 600000000,
      image: 'https://picsum.photos/500',
      price: 2000,
    },
    {
      id: 7,
      title: 'Pantoufles',
      subtitle: 'Pietro de Alchimist',
      date: Date.now() - 600000000,
      image: 'https://picsum.photos/500',
      price: 2000,
    },
    {
      id: 8,
      title: 'Pull en laine',
      subtitle: 'Pietro de Alchimist',
      date: Date.now() - 600000000,
      image: 'https://picsum.photos/500',
      price: 2000,
    },
  ],
  [
    {
      id: 9,
      title: 'Chaussettes',
      subtitle: 'Pietro de Alchimist',
      date: Date.now() - 800000000,
      image: 'https://picsum.photos/500',
      price: 2000,
    },
    {
      id: 10,
      title: 'Pantoufles',
      subtitle: 'Pietro de Alchimist',
      date: Date.now() - 800000000,
      image: 'https://picsum.photos/500',
      price: 2000,
    },
    {
      id: 11,
      title: 'Pull en laine',
      subtitle: 'Pietro de Alchimist',
      date: Date.now() - 800000000,
      image: 'https://picsum.photos/500',
      price: 2000,
    },
  ],
  [
    {
      id: 12,
      title: 'Chaussettes',
      subtitle: 'Pietro de Alchimist',
      date: Date.now() - 1000000000,
      image: 'https://picsum.photos/500',
      price: 2000,
    },
    {
      id: 13,
      title: 'Pantoufles',
      subtitle: 'Pietro de Alchimist',
      date: Date.now() - 1000000000,
      image: 'https://picsum.photos/500',
      price: 2000,
    },
    {
      id: 14,
      title: 'Pull en laine',
      subtitle: 'Pietro de Alchimist',
      date: Date.now() - 1000000000,
      image: 'https://picsum.photos/500',
      price: 2000,
    },
  ],
];

export {finalizedOffers};
